### ISSUE TITLE
The Youtube video in readme is private

### ISSUE THREAD

**Issue by xixiaofinland** [apex-enterprise-patterns/fflib-apex-common-samplecode#20]
The linked [YouTube video](http://www.youtube.com/watch?v=qlq46AEAlLI#t=572) in readme.md is in private mode.

Also the other video is unavailable: http://dreamforce.vidyard.com/watch/7QtP2628KmtXfmiwI-7B1w%20

**Comment by afawcett** [comment]
@xixiaofinland sad they appear to have been removed. I will remove from readme.
