### ISSUE TITLE
Error occurs during ant migration

### ISSUE THREAD

**Issue by Gayathri-D60** [apex-enterprise-patterns/fflib-apex-common-samplecode#25]
All Component Failures:
1.  flows/CreateCustomer.flow -- Error: Required field is missing: actionType (line 3, column 18)
2.  flows/CreatePolicy.flow -- Error: Required field is missing: actionType (line 3, column 18)
3.  flows/CustomerPolicy.flow -- Error: Required field is missing: actionType (line 3, column 18)
4.  flowDefinitions/CreateCustomer.flowDefinition -- Error: You can't create a flow definition directly through the API. A flow definition is created automatically when you create a new flow version.
5.  flowDefinitions/CreatePolicy.flowDefinition -- Error: You can't create a flow definition directly through the API. A flow definition is created automatically when you create a new flow version.
6.  flowDefinitions/CustomerPolicy.flowDefinition -- Error: You can't create a flow definition directly through the API. A flow definition is created automatically when you create a new flow version.
7.  classes/TestDataFactoryTest.cls -- Error: Page OrderDocument does not exist
8.  classes/UIAmbassadorController.cls -- Error: Page OrderDocument does not exist
9.  classes/UIAmbassadorControllerTest.cls -- Error: Page OrderDocument does not exist
10.  classes/UIAttachmentHandler.cls -- Error: Page OrderDocument does not exist
11.  classes/UIHomeController.cls -- Error: Page OrderDocument does not exist
12.  classes/UIHomeControllerTest.cls -- Error: Page OrderDocument does not exist
13.  classes/UIHomeLogin.cls -- Error: Page OrderDocument does not exist
14.  classes/UIHomeLoginTest.cls -- Error: Page OrderDocument does not exist
15.  classes/UINxtExtension.cls -- Error: Page OrderDocument does not exist
16.  classes/UINxtExtensionTest.cls -- Error: Page OrderDocument does not exist
17.  classes/UIRegisterExt.cls -- Error: Page OrderDocument does not exist
18.  classes/UIRegisterExtTest.cls -- Error: Page OrderDocument does not exist
19.  classes/UIResponse.cls -- Error: Page OrderDocument does not exist
20.  classes/UIResponseTest.cls -- Error: Page OrderDocument does not exist
21.  classes/UIResultWrapper.cls -- Error: Page OrderDocument does not exist
22.  classes/AddressUtility.cls -- Error: Page OrderDocument does not exist
23.  classes/AddressUtilityTest.cls -- Error: Page OrderDocument does not exist
24.  classes/Approved.cls -- Error: Page OrderDocument does not exist
25.  classes/AsyncScswAddresswareCom.cls -- Error: Page OrderDocument does not exist
26.  classes/NeoDigitalWrapperTest.cls -- Error: Page OrderDocument does not exist
27.  classes/OKKPolicyController.cls -- Error: Page OrderDocument does not exist
28.  classes/OKKPolicyControllerTest.cls -- Error: Page OrderDocument does not exist
29.  classes/ObjectBeforeTriggerTest.cls -- Error: Page OrderDocument does not exist
30.  classes/ObjectHandler.cls -- Error: Page OrderDocument does not exist
31.  classes/ObjectHandlerTest.cls -- Error: Page OrderDocument does not exist
32.  classes/ObjectUtility.cls -- Error: Page OrderDocument does not exist
33.  classes/ObjectUtilityTest.cls -- Error: Page OrderDocument does not exist
34.  classes/ObjectWrapper.cls -- Error: Page OrderDocument does not exist
35.  classes/ObjectWrapperTest.cls -- Error: Page OrderDocument does not exist
36.  classes/OnDemandRenewalScheduler.cls -- Error: Page OrderDocument does not exist
37.  classes/PDFRendering.cls -- Error: Page OrderDocument does not exist
38.  classes/PDFRenderingTest.cls -- Error: Page OrderDocument does not exist
39.  classes/PaymentProcessScheduler.cls -- Error: Page OrderDocument does not exist
40.  classes/PaymentUtility.cls -- Error: Page OrderDocument does not exist
41.  classes/PaymentUtilitytest.cls -- Error: Page OrderDocument does not exist
42.  classes/PolicyAfterTriggerTest.cls -- Error: Page OrderDocument does not exist
43.  classes/PolicyUtility.cls -- Error: Page OrderDocument does not exist
44.  classes/PolicyUtilityTest.cls -- Error: Page OrderDocument does not exist
45.  classes/PremiumCalculation.cls -- Error: Page OrderDocument does not exist
46.  classes/PremiumCalculationTest.cls -- Error: Page OrderDocument does not exist
47.  classes/PremiumWrapper.cls -- Error: Page OrderDocument does not exist
48.  classes/PremiumWrapperTest.cls -- Error: Page OrderDocument does not exist
49.  classes/Product2Utility.cls -- Error: Page OrderDocument does not exist
50.  classes/Product2UtilityTest.cls -- Error: Page OrderDocument does not exist
51.  classes/Product2Wrapper.cls -- Error: Page OrderDocument does not exist
52.  classes/Product2WrapperTest.cls -- Error: Page OrderDocument does not exist
53.  classes/ProductBeforeTriggerTest.cls -- Error: Page OrderDocument does not exist
54.  classes/AttachmentUtility.cls -- Error: Page OrderDocument does not exist
55.  classes/AttachmentUtilityTest.cls -- Error: Page OrderDocument does not exist
56.  classes/BatchEventPolicy.cls -- Error: Page OrderDocument does not exist
57.  classes/BatchEventPolicyTest.cls -- Error: Page OrderDocument does not exist
58.  classes/BatchEventRemainder.cls -- Error: Page OrderDocument does not exist
59.  classes/BatchFlatrateRenewal.cls -- Error: Page OrderDocument does not exist
60.  classes/BatchInsuredValueUpdate.cls -- Error: Page OrderDocument does not exist
61.  classes/BatchInvoiceProcess.cls -- Error: Page OrderDocument does not exist
62.  classes/BatchOnDemandRenewal.cls -- Error: Page OrderDocument does not exist
63.  classes/BatchPaymentFailure.cls -- Error: Page OrderDocument does not exist
64.  classes/BatchPaymentProcess.cls -- Error: Page OrderDocument does not exist
65.  classes/BatchPolicyRenewal.cls -- Error: Page OrderDocument does not exist
66.  classes/BatchWelcomeEmail.cls -- Error: Page OrderDocument does not exist
67.  classes/ClaimAfterTriggerTest.cls -- Error: Page OrderDocument does not exist
68.  classes/ClaimHandler.cls -- Error: Page OrderDocument does not exist
69.  classes/ClaimHandlerTest.cls -- Error: Page OrderDocument does not exist
70.  classes/ClaimSettle.cls -- Error: Page OrderDocument does not exist
71.  classes/ClaimUtility.cls -- Error: Page OrderDocument does not exist
72.  classes/ClaimUtilityTest.cls -- Error: Page OrderDocument does not exist
73.  classes/ComplaintWrapper.cls -- Error: Page OrderDocument does not exist
74.  classes/ComplaintWrappertest.cls -- Error: Page OrderDocument does not exist
75.  classes/Constants.cls -- Error: Page OrderDocument does not exist
76.  classes/ConstantsTest.cls -- Error: Page OrderDocument does not exist
77.  classes/ContactBeforeTriggerTest.cls -- Error: Page OrderDocument does not exist
78.  classes/DataHandler.cls -- Error: Page OrderDocument does not exist
79.  classes/DateUtility.cls -- Error: Page OrderDocument does not exist
80.  classes/DateUtilityTest.cls -- Error: Page OrderDocument does not exist
81.  classes/DraftApprove.cls -- Error: Page OrderDocument does not exist
82.  classes/EmailUtility.cls -- Error: Page OrderDocument does not exist
83.  classes/ProfileHandlerTest.cls -- Error: Page OrderDocument does not exist
84.  classes/ProfileWrapper.cls -- Error: Page OrderDocument does not exist
85.  classes/ProfileWrappertest.cls -- Error: Page OrderDocument does not exist
86.  classes/RVGPolicyController.cls -- Error: Page OrderDocument does not exist
87.  classes/RVGPolicyControllerTest.cls -- Error: Page OrderDocument does not exist
88.  classes/RegistrationController.cls -- Error: Page OrderDocument does not exist
89.  classes/RucksackAfterTriggerTest.cls -- Error: Page OrderDocument does not exist
90.  classes/RucksackHandler.cls -- Error: Page OrderDocument does not exist
91.  classes/RucksackHandlerTest.cls -- Error: Page OrderDocument does not exist
92.  classes/ProfileHandler.cls -- Error: Page OrderDocument does not exist
93.  classes/RucksackWrapper.cls -- Error: Page OrderDocument does not exist
94.  classes/RucksackWrapperTest.cls -- Error: Page OrderDocument does not exist
95.  classes/SaferpayWrapper.cls -- Error: Page OrderDocument does not exist
96.  classes/SaferpayWrapperTest.cls -- Error: Page OrderDocument does not exist
97.  classes/SearchUtility.cls -- Error: Page OrderDocument does not exist
98.  classes/SearchUtilityTest.cls -- Error: Page OrderDocument does not exist
99.  classes/SortUtility.cls -- Error: Page OrderDocument does not exist
100.  classes/SortUtilitytest.cls -- Error: Page OrderDocument does not exist
101.  classes/TestDataFactory.cls -- Error: Page OrderDocument does not exist
102.  classes/UIResultWrapperTest.cls -- Error: Page OrderDocument does not exist
103.  classes/UpdateFlag.cls -- Error: Page OrderDocument does not exist
104.  classes/UserPolicy.cls -- Error: Page OrderDocument does not exist
105.  classes/UserPolicyTest.cls -- Error: Page OrderDocument does not exist
106.  classes/Utility.cls -- Error: Page OrderDocument does not exist
107.  classes/UtilityTest.cls -- Error: Page OrderDocument does not exist
108.  classes/VoucherContactBeforeTriggerTest.cls -- Error: Page OrderDocument does not exist
109.  classes/WebServiceMockImpl.cls -- Error: Page OrderDocument does not exist
110.  classes/WelcomeEmailScheduler.cls -- Error: Page OrderDocument does not exist
111.  triggers/ClaimAfterTrigger.trigger -- Error: Variable does not exist: ClaimUtility (line 15, column 13)
112.  triggers/EventAfterTrigger.trigger -- Error: Variable does not exist: LingsApp (line 10, column 5)
113.  triggers/InvoiceAfterTrigger.trigger -- Error: Variable does not exist: ClaimUtility (line 15, column 9)
114.  triggers/ObjectBeforeTrigger.trigger -- Error: Variable does not exist: LingsApp (line 7, column 9)
115.  triggers/PolicyAfterTrigger.trigger -- Error: Variable does not exist: Constants (line 12, column 62)
116.  triggers/ProductBeforeTrigger.trigger -- Error: Variable does not exist: LingsApp (line 6, column 5)
117.  triggers/RucksackAfterTrigger.trigger -- Error: Variable does not exist: MobileAppUtility (line 13, column 4)
118.  triggers/LingsObjectAfterTrigger.trigger -- Error: Variable does not exist: LingsApp (line 7, column 5)
119.  classes/EmailUtilitytest.cls -- Error: Page OrderDocument does not exist
120.  classes/EventAfterTriggerTest.cls -- Error: Page OrderDocument does not exist
121.  classes/EventHandler.cls -- Error: Page OrderDocument does not exist
122.  classes/EventHandlerTest.cls -- Error: Page OrderDocument does not exist
123.  classes/EventPolicyScheduler.cls -- Error: Page OrderDocument does not exist
124.  classes/EventRemainderScheduler.cls -- Error: Page OrderDocument does not exist
125.  classes/EventUtility.cls -- Error: Page OrderDocument does not exist
126.  classes/EventUtilityTest.cls -- Error: Page OrderDocument does not exist
127.  classes/EventWrapper.cls -- Error: Page OrderDocument does not exist
128.  classes/EventWrapperTestClass.cls -- Error: Page OrderDocument does not exist
129.  classes/ExceptionUtility.cls -- Error: Page OrderDocument does not exist
130.  classes/ExceptionUtilityTest.cls -- Error: Page OrderDocument does not exist
131.  classes/ForgotPasswordController.cls -- Error: Page OrderDocument does not exist
132.  classes/ForgotPasswordControllerTest.cls -- Error: Page OrderDocument does not exist
133.  classes/InvoiceAfterTriggerTest.cls -- Error: Page OrderDocument does not exist
134.  classes/InvoiceController.cls -- Error: Page OrderDocument does not exist
135.  classes/InvoiceProcessScheduler.cls -- Error: Page OrderDocument does not exist
136.  classes/LingsApp.cls -- Error: Page OrderDocument does not exist
137.  classes/LingsApptest.cls -- Error: Page OrderDocument does not exist
138.  classes/LingsCalloutMock.cls -- Error: Page OrderDocument does not exist
139.  classes/LingsCalloutMock1.cls -- Error: Page OrderDocument does not exist
140.  classes/LingsObjectAfterTriggerTest.cls -- Error: Page OrderDocument does not exist
141.  classes/LinkClaimAttachmentTest.cls -- Error: Page OrderDocument does not exist
142.  classes/MobileAppUtility.cls -- Error: Page OrderDocument does not exist
143.  classes/MobileAppUtilityTest.cls -- Error: Page OrderDocument does not exist
144.  classes/MobileUtility.cls -- Error: Page OrderDocument does not exist
145.  classes/MobileUtilityTest.cls -- Error: Page OrderDocument does not exist
146.  classes/MyProfilePageController.cls -- Error: Page OrderDocument does not exist
147.  classes/MyProfilePageControllerTest.cls -- Error: Page OrderDocument does not exist
148.  classes/NeoDigitalCreateClaimTest.cls -- Error: Page OrderDocument does not exist
149.  classes/NeoDigitalCreateClaim.cls -- Error: Page OrderDocument does not exist
150.  classes/NeoDigitalCreateCustomer.cls -- Error: Page OrderDocument does not exist
151.  classes/NeoDigitalCreateCustomerController.cls -- Error: Page OrderDocument does not exist
152.  classes/NeoDigitalCreateCustomerTest.cls -- Error: Page OrderDocument does not exist
153.  classes/NeoDigitalCreatePolicy.cls -- Error: Page OrderDocument does not exist
154.  classes/NeoDigitalCreatePolicytest.cls -- Error: Page OrderDocument does not exist
155.  classes/NeoDigitalPolicyRequestWrapper.cls -- Error: Page OrderDocument does not exist
156.  classes/NeoDigitalRequestWrapper.cls -- Error: Page OrderDocument does not exist
157.  classes/NeoDigitalResponseWrapper.cls -- Error: Page OrderDocument does not exist
158.  classes/NeoDigitalWrapper.cls -- Error: Page OrderDocument does not exist
159.  classes/NeoDigitalWrapperClaim.cls -- Error: Page OrderDocument does not exist
160.  classes/NeoDigitalWrapperCustomer.cls -- Error: Page OrderDocument does not exist
161.  classes/NeoDigitalWrapperPolicy.cls -- Error: Page OrderDocument does not exist
162.  aura/ApproveProduct/ApproveProduct.cmp -- Error: Invalid definition for Approved: ApexService.getType() return null with currentNamespace: c, namespace: null, name: Approved
163.  pages/Beratungsprotokoll.page -- Error: Apex class 'BeratungsprotokollExt' does not exist
164.  pages/InvoicePage.page -- Error: Apex class 'InvoiceController' does not exist
165.  pages/NeoDigitalCustomer.page -- Error: Apex class 'NeoDigitalCreateCustomerController' does not exist
166.  pages/OKKPolicy.page -- Error: Apex class 'OKKPolicyController' does not exist
167.  pages/Policy.page -- Error: Apex class 'UserPolicy' does not exist
168.  pages/RVGPolicy.page -- Error: Apex class 'RVGPolicyController' does not exist
169.  pages/RegistrationPage.page -- Error: Apex class 'RegistrationController' does not exist
170.  pages/UIHome.page -- Error: Apex class 'UIHomeController' does not exist
171.  flows/Claim_Updates.flow -- Error: myRule_1_A2 (Action) - We can't find an action with the name and action type that you specified.

**Comment by daveespo** [comment]
I don't believe this issue belongs in this project's issue tracker. The list of metadata components in the error message are not part of the fflib-apex-common-samplecode project
