### ISSUE TITLE
Deploy does not work -  Class InvoicingServiceImpl : Illegal assignment from fflib_IDomain to fflib_ISObjectDomain

### ISSUE THREAD

**Issue by jinlii** [apex-enterprise-patterns/fflib-apex-common-samplecode#34]
Deploy to salesforce gave a bunch of errors. They all seem to be around  Class InvoicingServiceImpl : Illegal assignment from fflib_IDomain to fflib_ISObjectDomain.

Can you please fix it so that I can deploy?

**Comment by jinlii** [comment]
Additional errors:
deploy/triggers/DeveloperWorkItems.trigger(31,37):Invalid type: DeveloperWorkItems
deploy/triggers/OpportunityLineItems.trigger(31,37):Invalid type: OpportunityLineItems
deploy/pages/opportunityapplydiscount.page(opportunityapplydiscount):Apex class 'OpportunityApplyDiscountController' does not exist
deploy/pages/opportunityapplydiscounts.page(opportunityapplydiscounts):Apex class 'OpportunityApplyDiscountController' does not exist
deploy/pages/opportunitycreateinvoice.page(opportunitycreateinvoice):Apex class 'OpportunityCreateInvoiceController' does not exist
deploy/pages/opportunitycreateinvoices.page(opportunitycreateinvoices):Apex class 'OpportunityCreateInvoiceController' does not exist
deploy/pages/opportunityinvoicing.page(opportunityinvoicing):Apex class 'OpportunityInvoicingController' does not exist
deploy/triggers/Opportunities.trigger(31,37):Invalid type: Opportunities

**Comment by stohn777** [comment]
@jinlii 
Unfortunately you're caught at a point where Sample Code is out of sync with Commons.  Until we review and merge an existing PR, please deploy the code for PR 31 [1]. 

My apology for the inconvenience.

@daveespo, @ImJohnMDaniel -- We need to prioritize getting PR 31 reviewed and merged.

[1] https://github.com/apex-enterprise-patterns/fflib-apex-common-samplecode/pull/31

**Comment by stohn777** [comment]
@jinlii 
[PR #31](https://github.com/apex-enterprise-patterns/fflib-apex-common-samplecode/pull/31) was merged, so you should be able to install from "master" now.
