### ISSUE TITLE
Example of before insert trigger

### ISSUE THREAD

**Issue by loganm** [apex-enterprise-patterns/fflib-apex-common-samplecode#7]
Because records in a before insert/before update trigger should not be updated, it would be good to have an example of how to deal with them. The sample code only contains examples of on after trigger events that pair nicely with UoW and other domains.

**Comment by afawcett** [comment]
Do you mean how to override the onBeforeInsert and onBeforeUpdate base class methods?

**Comment by loganm** [comment]
That's the one. I've found that doing onBefore methods requires some extra consideration over the onAfter methods. Mainly because changes made to the records in an onBefore trigger are automatically committed at the end of the transaction, and registering the record as dirty throws a dml exception.

I've been writing procedural code in the onBefore method (maybe private methods where it makes sense) to avoid using the public domain methods, and I just have a gut feeling it's not the best way to use the patterns.

I'm interested in how you'd deal with onBefore methods to gauge whether I'm on the right path or not.

**Comment by afawcett** [comment]
Ok i think i've getting the gist (no pun intended) of the kind of sample you want to see. Can you provide a small sudo example perhaps to help me nail what your currently doing in my mind?
